### PR TITLE
add first lab work

### PR DESCRIPTION
**Pull request by KaJo313**

### CODE REVIEW

**Comment by KaJo313** [comment]
Contains Labs 1 & 2

**Comment by KaJo313** [comment]
Didn't fulfill all of the specs for Lab 2, but wanted to get my work so far to you.

**Review by DavidIValencia — APPROVED** [review]
The sign-in form looks fantastic!

The pirate ipsum leaves some to be desired. You have the floated photos, but you should probably make a container for them to sit in which is relative and then rotate them using https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate.

**Review by DavidIValencia — APPROVED** [review]
Decent job on this, a lot of the major elements are there. The footer should be positioned on the bottom after the other elements instead of being fixed. The top links on desktop view should be spaced further apart. On the mobile view, the container should stretch across the entire width of the page.

**Pull request merged**
